### ISSUE TITLE
hi, im one of your bot user

### ISSUE THREAD

**Issue by azrulshah** [little-fort/booster-bot#1]
any news for conquest gameplay?

**Comment by little-fort** [comment]
Hi! Conquest proved a bit trickier than expected because the post-match screens have different patterns based on whether you win or lose, and the timings of those patterns are a bit inconsistent. I have some changes that I was testing a couple weeks ago but have not had time to get back to it since. Should hopefully have more time to get back to it in the next week or so

**Comment by little-fort** [comment]
Hi, I have published a new [release preview](https://github.com/little-fort/booster-bot/releases/tag/v1.2.0-preview) that I could use some feedback on. The big changes include support for farming Conquest mode (Proving Grounds only for now) and significantly improved consistency with the app's ability to detect game state and play cards.

For now, all the good changes were only applied to the new Conquest farming mode—the Ranked farming mode logic is unchanged. But if all goes well, I should have the Ranked logic reworked in the next couple days, and then I'll publish an official release.

In the meantime, it would be helpful if you could try out the preview build and let me know what you think!

**Comment by azrulshah** [comment]
```
[2023-07-31 08:43:24] Checking for active Conquest lobby...
Parameter is not valid.

   at System.Drawing.Bitmap..ctor(String filename)
   at BoosterBot.ImageUtilities.ReadArea(Int32 x, Int32 y, Int32 width, Int32 height, Boolean export, String image, String expected, Boolean preproc) in D:\a\booster-bot\booster-bot\src\BoosterBot\Helpers\ImageUtilities.cs:line 142
   at BoosterBot.ImageUtilities.ReadArea(Rect crop, String image, Int32 sampleCount, Boolean export, String expected) in D:\a\booster-bot\booster-bot\src\BoosterBot\Helpers\ImageUtilities.cs:line 120
   at BoosterBot.ConquestBot.SelectLobby() in D:\a\booster-bot\booster-bot\src\BoosterBot\ConquestBot.cs:line 194
   at BoosterBot.ConquestBot.RunMatchLoop() in D:\a\booster-bot\booster-bot\src\BoosterBot\ConquestBot.cs:line 136
   at BoosterBot.ConquestBot.Run() in D:\a\booster-bot\booster-bot\src\BoosterBot\ConquestBot.cs:line 53
   at BoosterBot.Program.Main(String[] args) in D:\a\booster-bot\booster-bot\src\BoosterBot\Program.cs:line 74

Press [Enter] to continue...
```

stuck after 1 stage of conquest

**Comment by little-fort** [comment]
Well that's new... Are you consistently seeing that error on every attempt? And are you running in fullscreen mode?

**Comment by azrulshah** [comment]
> Well that's new... Are you consistently seeing that error on every attempt? And are you running in fullscreen mode?

ok now it can move by itself but, it can only play in silver only, means even i have ticket i cant move to gold level, am i right?

**Comment by little-fort** [comment]
1. I see the issue that caused the first error you saw, I should have a patch for that shortly.
2. When the bot starts a fresh run, it will only target Proving Grounds by default. I will add more options to let you also target Silver/Gold if you have tickets, but that will come in a later update. I don't want to make that the default behavior because not everybody would want to automatically use tickets

**Comment by azrulshah** [comment]
for no1 thanks, for 2 i dont mind if its only can play silver, just asking "is that how the bot should play?" cuz u ask me to test right? :)

**Comment by little-fort** [comment]
Haha yes, this is all helpful! I just want to confirm that when you see the bot starting new matches, it's starting in _Proving Grounds_ lobbies, not using up _Silver_ tickets, right?

**Comment by azrulshah** [comment]
> Haha yes, this is all helpful! I just want to confirm that when you see the bot starting new matches, it's starting in _Proving Grounds_ lobbies, not using up _Silver_ tickets, right?

yes

**Comment by little-fort** [comment]
Updated preview build with fixes: 
https://github.com/little-fort/booster-bot/releases/tag/v1.2.0-preview.2

**Comment by little-fort** [comment]
Updated release that has options to farm all levels of Conquest:
https://github.com/little-fort/booster-bot/releases/tag/v1.3.0
