### ISSUE TITLE
Conquest mode not queuing

### ISSUE THREAD

**Issue by Frritz** [little-fort/booster-bot#19]
I had been using the 1.3.0 preview to farm different levels of conquest for extended periods but now for some reason it does not make it to the 1st match.
It queues up fine but then once it starts waiting for an opponent it thinks that it's in a game immediately so it snaps and then sees it isn't in a game and cancels matchmaking after 21 seconds to look for the main menu.
So it seems like it's skipping the step to wait for an opponent and confirm it's in a match.
I've attached a log where I am queuing into conquest where proving grounds was already selected, but it does the same thing even if no conquest is currently active.
Nothing has changed on the system it's running on except updating snap.
[log.txt](https://github.com/little-fort/booster-bot/files/12297339/log.txt)

**Comment by little-fort** [comment]
Thanks for the heads up! Here's a fixed release: https://github.com/little-fort/booster-bot/releases/tag/v1.3.1

Today's update moved the 'Cancel' button down a few pixels and it broke the detection, but should be good now.

**Comment by Frritz** [comment]
That seems to have fixed it.
I figured it must be something with the game but that was such a subtle change I didn't even notice.
Thanks.
