### ISSUE TITLE
Could not detect main menu

### ISSUE THREAD

**Issue by toshiro9117** [little-fort/booster-bot#26]
Starting Conquest bot...
[2023-08-26 14:11:53] Could not detect main menu (attempt #1). Trying again in 5 seconds...
[2023-08-26 14:12:01] Could not detect main menu (attempt #2). Trying again in 5 seconds...
[2023-08-26 14:12:10] Attempting to determine loop entry point...
[2023-08-26 14:12:17] Attempting blind reset clicks...
[2023-08-26 14:12:27] Attempting to determine loop entry point...
[2023-08-26 14:12:34] Attempting blind reset clicks...
[2023-08-26 14:12:45] Attempting to determine loop entry point

**Comment by little-fort** [comment]
Are you using the new default PC UI from the latest update?

**Comment by toshiro9117** [comment]
> Are you using the new PC UI from the latest update?

This one?
https://imgur.com/a/uHPwyf9

**Comment by Ramzh** [comment]
might be the resolution of the screen. I had the same issue and reducing from 1440p to 1080p worked. On that note any plans to support other resolutions?

**Comment by toshiro9117** [comment]
> might be the resolution of the screen. I had the same issue and reducing from 1440p to 1080p worked. On that note any plans to support other resolutions?

i use 1080p though

**Comment by d1g1t1z3d** [comment]
Turning off 'Landscape' mode in the options worked for me.

**Comment by little-fort** [comment]
> > Are you using the new PC UI from the latest update?
> 
> This one?
> https://imgur.com/a/uHPwyf9

Okay that's the correct UI to use. What is your system display scaling set to?

**Comment by toshiro9117** [comment]
> > This one?
> > https://imgur.com/a/uHPwyf9
> 
> Okay that's the correct UI to use. What is your system display scaling set to?

its ok now, my laptop scaling was 125% then i turn it to 100%

**Comment by azrulshah** [comment]
is the bot working with the new pc version?

**Comment by toshiro9117** [comment]
> is the bot working with the new pc version?

yes

**Comment by little-fort** [comment]
> is the bot working with the new pc version?

Just to clarify, yes it's working, you just have to disable "Landscape" mode in the settings

**Comment by toshiro9117** [comment]
> > is the bot working with the new pc version?
> 
> Just to clarify, yes it's working, you just have to disable "Landscape" mode in the settings

yep... check your scaling if it is 100% if it is then run the bot then disable landscape and your good to go.
