### ISSUE TITLE
Agatha interaction 

### ISSUE THREAD

**Issue by Mrstunk** [little-fort/booster-bot#44]
Not super important, but Agatha no longer works with auto retreat. When setting auto retreat after 3 or 4 the bot somehow retreat after two or even one turn. V1.4.0 still works perfectly fine with Agatha.

**Comment by little-fort** [comment]
Hi, thanks for pointing that out. New release is up that should fix this issue:

https://github.com/little-fort/booster-bot/releases/tag/v1.4.3
