### ISSUE TITLE
Play cards not working

### ISSUE THREAD

**Issue by snaptools2023** [little-fort/booster-bot#48]
I have tested on 2 computers and it looks like the "Play Cards" functionality is not working for me anymore.  Button clicks all work.  Conquest gets started and it will snap and end the turn, but the "Left Mouse Button Down" doesn't seem to be working so no cards ever get played.  

Tested on windows 10 and windows 11.

The [PlayCard](https://github.com/little-fort/booster-bot/blob/aaf7ed51d029c9648c93bc4c984b07932fa7ceeb/src/BoosterBot/Helpers/SystemUtilities.cs#L91C24-L91C32) method seems to be correct and wouldn't stop working because of the win32 api.  I am not sure how/what they did to prevent this from working.

Are you seeing the same issue?

**Comment by little-fort** [comment]
Thanks for the heads up, yeah I'm seeing it too This was definitely working before the last patch. I'll play around with it today and see if I can get it working again

**Comment by little-fort** [comment]
Fixed: https://github.com/little-fort/booster-bot/releases/tag/v1.4.5

**Comment by snaptools2023** [comment]
This is working for me, also.  Thank you for taking the time to fix this.
