### ISSUE TITLE
Issue with Conquest Mode Progression

### ISSUE THREAD

**Issue by Pokemen** [little-fort/booster-bot#50]
Hello,

First, I would like to express my gratitude. During use, when I win a Conquest mode and receive a silver ticket, it cannot proceed further. Is this issue unique to me, or is it a known problem? 

Thank you.

**Comment by little-fort** [comment]
Hi, thanks for reporting this. This happens every few patches as they shift some of the UI elements around.

I've put up a new build with a fix for this, let me know if it resolves the issue for you:
https://github.com/little-fort/booster-bot/releases/tag/v1.4.6

**Comment by snaptools2023** [comment]
I see this bug from time to time.  It is like it "misses" a button click and just starts swiping left to find that play button on the conquest level screen.  I dont know if its a timing thing but its one of those difficult to track bugs because it doesnt happen often.
