### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by Lyn8051** [little-fort/booster-bot#59]
Hello, I used your script, and at first, I couldn't move the mouse properly. After switching to run it in administrator mode, I could move the mouse, but I couldn't click in the game. The mouse moves to the right place, and the script shows that it has clicked, but the game doesn't respond. Do you know how to solve this?

**Comment by little-fort** [comment]
Very odd. I encountered this once before but haven't received any reports since of this since I last fixed it and I am unable to replicate it. Could you try it again and upload the generated log file? Should be in the `logs` directory of the application

**Comment by snaptools2023** [comment]
@Lyn8051  can we close this issue?

**Comment by Lyn8051** [comment]
Yes, thank you very much!



---Original---
From: ***@***.***&gt;
Date: Sat, Nov 16, 2024 06:36 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [little-fort/booster-bot] QUESTION (Issue #59)




 
@Lyn8051  can we close this issue?
