### ISSUE TITLE
My script cannot run properly

### ISSUE THREAD

**Issue by nevaeHnIedaM** [little-fort/booster-bot#61]
I set the resolution correctly, but the script always couldn't recognize the main menu. My laptop has native 2K graphics and a 16:9 ratio with 240Hz. I tried adjusting the refresh rate to 60Hz, but still couldn't use it. I ran it in the Chinese version, and even when I tried the Steam version, it didn't work. It always clicked on strange interfaces
![123](https://github.com/user-attachments/assets/39602380-9a54-4845-9425-3b69bd36266e)

**Comment by nevaeHnIedaM** [comment]
![333](https://github.com/user-attachments/assets/eb871b70-115d-441f-a4cd-685647c94cf1)

**Comment by little-fort** [comment]
In the Display Properties menu, what is your system's 'Scale' value set to?

**Comment by nevaeHnIedaM** [comment]
> Hi, refresh rate shouldn't be a factor, you can leave it at 240hz. In the Display settings menu, what is your system's 'Scale' value set to?

My system has been scaled to 100% and the resolution has been adjusted to 1920 * 1080

**Comment by nevaeHnIedaM** [comment]
> Hi, refresh rate shouldn't be a factor, you can leave it at 240hz. In the Display settings menu, what is your system's 'Scale' value set to?

Brother, can you use remote control to manipulate my computer and help me research? I am a computer science student and I have tried many ways I can think of, but none of them can solve this problem

**Comment by nevaeHnIedaM** [comment]
> Hi, refresh rate shouldn't be a factor, you can leave it at 240hz. In the Display settings menu, what is your system's 'Scale' value set to?

I think the problem lies in recognition rather than resolution, it always shows that the main interface cannot be recognized

**Comment by little-fort** [comment]
> I think the problem lies in recognition rather than resolution, it always shows that the main interface cannot be recognized

You may be right. First, give the bot a fresh run from the main menu. After it fails, then go into the application directory, pack the `screens`  directory into a .zip archive, and upload it here. This will help me see what the bot is "seeing"

**Comment by nevaeHnIedaM** [comment]
Brother, thank you very much for being willing to help me. I tried to write a simple version using scripting software, but the efficiency was extremely low. I 
[screens.zip](https://github.com/user-attachments/files/17187910/screens.zip)
have uploaded my problematic booster bot and hope you can solve the problem through it

My laptop screen has a 16:9 ratio, and I'm not sure if it's related to this factor. In China, many people are using your script and haven't encountered my problem

**Comment by little-fort** [comment]
Okay I might know what's going on. I think the downscaling from running your display at 1080p might be distorting the view just enough for the image recognition to miss the intended thresholds. If so, I can add a new startup option to account for this, but I will need your help collecting data on the expected values. Download this dev build, then try running it and send me the latest log file from the `logs` directory after it's done:

https://github.com/little-fort/booster-bot/releases/tag/v1.4.10-dev.1

**Comment by nevaeHnIedaM** [comment]
Latest log files
[ladder-log-20241001144117.txt](https://github.com/user-attachments/files/17200729/ladder-log-20241001144117.txt)

**Comment by little-fort** [comment]
Yeah okay, that was the issue. Unfortunately, I can't add a global fix for this because that could cause unstable behavior for everyone who's not using a downscaled display. But I can add a startup flag so that you can run the bot in "downscaled mode". This means every time you run it, you will have to open your terminal in the app directory, and then start the app from the command line like so: `BoosterBot.exe -d`

Here's another dev build:

https://github.com/little-fort/booster-bot/releases/tag/v1.4.10-dev.2

Let me know if this is able to start the core loop and play matches

**Comment by nevaeHnIedaM** [comment]
> Yeah okay, that was the issue. Unfortunately, I can't add a global fix for this because that could cause unstable behavior for everyone who's not using a downscaled display. But I can add a startup flag so that you can run the bot in "downscaled mode". This means every time you run it, you will have to open your terminal in the app directory, and then start the app from the command line like so: `BoosterBot.exe -d`
> 
> Here's another dev build:
> 
> https://github.com/little-fort/booster-bot/releases/tag/v1.4.10-dev.2
> 
> Let me know if this is able to start the core loop and play matches

Thank you, brother. It can be used normally now. Thank you again
![image](https://github.com/user-attachments/assets/be11fd4c-6c2c-4c42-b640-aaf0280e1373)

**Comment by nevaeHnIedaM** [comment]
Oh no, brother, you can start the duel normally now, but you won't be able to drag the cards

**Comment by little-fort** [comment]
Great! I'm glad to hear it, brother. 😁 Here is an official release that will keep the same function but will disable the extra logging that was needed for debugging:

https://github.com/little-fort/booster-bot/releases/tag/v1.4.10

Let me know if you run into any more issues!
