### ISSUE TITLE
Not an issue - More of an alert

### ISSUE THREAD

**Issue by snaptools2023** [little-fort/booster-bot#65]
In the meantime, before a fix for high voltage is fixed, you can use the Deadpool Diner result to still play conquest.  It might be tricky to configure, but it might be nice to have a flag to pick where the conquest button is?

**Comment by little-fort** [comment]
Hi, new release is up:

https://github.com/little-fort/booster-bot/releases/tag/v1.4.11

This will change the default click point for the Conquest button to account for the current event, and I also added a `-e`/`--event` startup parameter that could be used to manually adjust the click point for events in future releases

**Comment by snaptools2023** [comment]
New release looks fantastic.  Thanks for your work on this.
