### ISSUE TITLE
Please Consider Enabling Bot Support in High Voltage Mode

### ISSUE THREAD

**Issue by QingXu51820** [little-fort/booster-bot#66]
The tasks in High Voltage Mode can be quite challenging to complete manually.It would be incredibly helpful if there were bot support to assist in automating some of these tasks.

**Comment by little-fort** [comment]
Hi, thanks for the suggestion. I've published a new release with added support for farming limited time modes:

https://github.com/little-fort/booster-bot/releases/tag/v1.4.11

**Comment by QingXu51820** [comment]
Thank you so much for the update! The bot is running smoothly and has helped me a lot. I really appreciate your hard work, it has been a huge help!
