### ISSUE TITLE
can play 2K分辨率?

### ISSUE THREAD

**Issue by Lau-ZZR** [little-fort/booster-bot#72]
你好作者，可以支持一下PC端2K分辨率吗谢谢

**Comment by Lau-ZZR** [comment]
Hello author, can you support 2K resolution on PC? Thank you

**Comment by little-fort** [comment]
Hi, thank you for your suggestion. Unfortunately, I don't have plans to support higher resolutions at this time. The bot relies on precise window coordinates to detect all of the UI reference points, and adding support for 2K or 4K resolutions would mean having to reconfigure and retest every internal function of the bot. I may try to revisit this idea in the future, but I don't have the time to handle it right now

**Comment by Lau-ZZR** [comment]
我已收到您的邮件。

**Comment by snaptools2023** [comment]
It looks like support for higher resolutions is not in the works yet.  Please close this issue.
