### ISSUE TITLE
My script cannot run properly

### ISSUE THREAD

**Issue by jrich587** [little-fort/booster-bot#73]
I set the resolution correctly, but the script can't recognize the main menu no matter what I do. My resolution is 1920 x 1080, and my scale is 100% I am on the steam version, I have also tried using the downscaling command in command prompt from where the exe is located.
[screens.zip](https://github.com/user-attachments/files/17716354/screens.zip)
[logs.zip](https://github.com/user-attachments/files/17716357/logs.zip)
![image](https://github.com/user-attachments/assets/848c81b9-783e-48a2-aa74-e554b73aa85f)
[hotkey.txt](https://github.com/user-attachments/files/17716374/hotkey.txt)
[ladder-log-20241112220551.txt](https://github.com/user-attachments/files/17716375/ladder-log-20241112220551.txt)
[ladder-log-20241112220443.txt](https://github.com/user-attachments/files/17716376/ladder-log-20241112220443.txt)
[ladder-log-20241112215722.txt](https://github.com/user-attachments/files/17716377/ladder-log-20241112215722.txt)
[conquest-log-20241112214023.txt](https://github.com/user-attachments/files/17716378/conquest-log-20241112214023.txt)
[event-log-20241112213928.txt](https://github.com/user-attachments/files/17716379/event-log-20241112213928.txt)
I added the logs twice, a compilation of all of them in the zip folder and separately above this.
I would really appreciate some help. I have also set my marvel snap to portrait mode instead of landscape
![image](https://github.com/user-attachments/assets/82cc9d60-5e00-4262-bb62-13ac34b72833)

**Comment by Kusaki-Y** [comment]
![0](https://github.com/user-attachments/assets/4efd042b-e286-49d8-bc78-ed3bca8bb6bf)

**Comment by little-fort** [comment]
@jrich587 Just to clarify, are you running the game in fullscreen?

**Comment by jrich587** [comment]
@little-fort I will try running the game in fullscreen and report back to you when I can later on today. I reckon that I probably haven't been running the game in fullscreen.
