### ISSUE TITLE
After the Nov 12 patch, the script is unable to run continuously in Conquest mode.

### ISSUE THREAD

**Issue by A1C4-R** [little-fort/booster-bot#74]
Thank you very much for creating this script! I may have used it for over a thousand hours, and I truly appreciate your contribution to simplifying the game. However, after the recent patch (Nov 12, 2024), my friends and I have encountered an issue where the script cannot run continuously: it stops at the alliance panel after finished one Conquest game, unable to proceed further. We have to restart the script each time this happens. Have you noticed similar issues? Is this due to an intervention by SD, or is it just a bit of bad luck for my friends and me? Thank you in advance for your response.

**Comment by snaptools2023** [comment]
This randomly happens to me from time to time.  It has been happening forever, though.  The console says the bot is hopelessly lost and exits.  I am surprised that hitting the escape key doesnt exit the alliance screen, so I do not have any tips on why this happens.

**Comment by A1C4-R** [comment]
Thank you so much! lokking forward to see the updates!

**Comment by little-fort** [comment]
New release is up: https://github.com/little-fort/booster-bot/releases/tag/v1.5.1

Give it a try and let me know if it solves this issue for you

**Comment by A1C4-R** [comment]
Thank you very much! I will have a try later today and give you a feedback ASAP! :D

**Comment by A1C4-R** [comment]
> New release is up: https://github.com/little-fort/booster-bot/releases/tag/v1.5.1
> 
> Give it a try and let me know if it solves this issue for you

I ran the scipt for the whole night(6 hours), and it ran perfectly well. But the morning I woke up and claimed several rewards it couldn't redirect to the conquest page (always stuck to the alliance page),  and the script can run properly after restarting both the game and script. The stablity is well improved in a general way after the update. 

Once again, on behalf of my community and my friends, I sincerely thank you for your contributions. If there is anything I can assist you with, please do not hesitate to let me know. Wishing you a wonderful day.

**Comment by Avrizinth** [comment]
I also may have preemptively claimed it was resolved as well.  It worked perfectly fine until this morning.  Now it is suffering from the exact same error as before.

**Comment by little-fort** [comment]
@A1C4-R @Avrizinth Thank you both for your reports, I have published a new release: https://github.com/little-fort/booster-bot/releases/tag/v1.5.2

This should resolve the issue causing the bot to get stuck on the Alliances page. Give it a try and let me know if you experience additional issues

**Comment by A1C4-R** [comment]
@little-fort I am so surprised to see the update, I'll try to run this script for the whole night to test if it runs correctly, thank you again!

**Comment by Avrizinth** [comment]
Ran continuously, no issues.

**Comment by A1C4-R** [comment]
@little-fort it ran perfectly! thank you very much!
