### ISSUE TITLE
BoosterBot moves to Alliance Tab and breaks continuously

### ISSUE THREAD

**Issue by Avrizinth** [little-fort/booster-bot#76]
This has been happening for about 7 or 8 days.  The bot will finish a match, and move to the alliance tab (even without a single active alliance quest) and just stay on that tab forever.

**Comment by snaptools2023** [comment]
This is a duplicate of #74

**Comment by little-fort** [comment]
Hi, please try again with the latest release and let me know if you are still encountering issues: 

https://github.com/little-fort/booster-bot/releases/tag/v1.5.1

**Comment by Avrizinth** [comment]
The issue appears to be resolved.
