### ISSUE TITLE
SnapCN's font style has been changed.

### ISSUE THREAD

**Issue by Kusaki-Y** [little-fort/booster-bot#79]
![Screenshot_漫威终极逆转_20241121_083306](https://github.com/user-attachments/assets/a24fff29-0126-4d5f-a6f1-9e5e5c0ec706)
![Screenshot_漫威终极逆转_20241121_083216](https://github.com/user-attachments/assets/05bdd36b-78c1-4264-bd8d-ad9184c29988)
![Screenshot_漫威终极逆转_20241121_083211](https://github.com/user-attachments/assets/13fb9e73-b2e4-4377-9a24-d7d7178ffc0f)
![Screenshot_漫威终极逆转_20241121_083209](https://github.com/user-attachments/assets/6071bcf8-f770-4e28-b21b-6fd430d96a3d)
![Screenshot_漫威终极逆转_20241121_083200](https://github.com/user-attachments/assets/2e576c0b-5f2b-4d4b-87ca-afbacf28dcea)

**Comment by sakura0423** [comment]
Help us plz

**Comment by Kusaki-Y** [comment]
Will this be solved if I replace the figure in the reference folder with the latest figure?

**Comment by sakura0423** [comment]
> Will this be solved if I replace the figure in the reference folder with the latest figure?

I think that's a good way to go. The problem I'm having is that I don't know what to do with the images, I see that the images under the ref path are transformed

**Comment by Kusaki-Y** [comment]
I discovered the connection between picture and gaming interfaces. The picture is a screenshot taken at 1920*1080 resolution. So, if you re-crop the image according to size, it should be able to be used normally, right?

**Comment by ywj87132749** [comment]
After today's update, scripts can no longer be automatically executed

**Comment by little-fort** [comment]
Wow that is unfortunate, I have no idea why the devs would do that. I am almost wondering if it's a bug because it looks completely inconsistent with the game's overall design.

> Will this be solved if I replace the figure in the reference folder with the latest figure?

Yes! The bot takes crops of the game screen at runtime and saves them to the `screens` folder. These are then matched with the images in the `reference` folder to infer the game state. If you update the base image in the `reference` folder to be the version with the CN font, then the bot will use that as the point of reference.

If you (or any other CN players) can correctly map and update the reference images, it should restore functionality. Then if you share them here, I can add the CN versions to the source code to be included in future releases. I don't have access to the CN version of the game so I can't do it myself

**Comment by snaptools2023** [comment]
It looks like it is not loading the font resource correctly.  Can you uninstall and reinstall SNAP?

**Comment by little-fort** [comment]
> It looks like it is not loading the font resource correctly. Can you uninstall and reinstall SNAP?

I would also recommend trying this. That font looks like it could be the default Unity font, which could indicate something broke with rendering text

**Comment by Kusaki-Y** [comment]
Everyone has this problem, it may be caused by the game update, I am trying to replace the pictures, but there are still some problems.

**Comment by Kusaki-Y** [comment]
> > It looks like it is not loading the font resource correctly. Can you uninstall and reinstall SNAP?
> 
> I would also recommend trying this. That font looks like it could be the default system font, which could indicate something broke with rendering text

I have another question, if I replace the previous file with a Chinese picture, will the program still run normally?

**Comment by little-fort** [comment]
> I have another question, if I replace the previous file with a Chinese picture, will the program still run normally?

Yes, as long as the reference images were updated to match what the game is displaying, the program will function fine. It does not need to be in English

**Comment by holletian** [comment]
> > > 还有一个问题，如果我把之前的文件替换成中文图片，程序还能正常运行吗？
> > 
> > 
> > 是的，只要更新参考图像以匹配游戏显示的内容，程序就可以正常运行。它不需要是英文的
> 
> 我替换了大约一半的图像，但其中许多图像在屏幕文件夹中丢失了。现在该程序在某些屏幕上可以工作，但在战斗屏幕上则不行。该程序不会在其回合中打牌或撤退，我该如何解决这个问题？
You try to share the main program with the author. See if we can solve this problem

**Comment by little-fort** [comment]
> I replaced about half of the images but many of them are missing in the screen folders. Now the program works on some screens but not the battle screens. The program will not play cards or retreat on its turn, how can I fix this?

You can't replace them all at once, you have to make sure to replace the original reference with a cropped image that is displaying the same UI element that the original reference image was displaying.

For example, if you wanted to update the `lbl-conquest-pg-1-preproc.png` image, you would have to run the bot in Conquest mode, wait until it reaches the Proving Grounds lobby screen, and then take the image that it captured from that view.

So while it is possible, I do think this would be a difficult task for someone who doesn't really understand the bot's operation. I have an idea on how I could build in a self-configuration tool so everyone can fix it on their own, but it will take me some time to put that together.

**Comment by Kusaki-Y** [comment]
> > I replaced about half of the images but many of them are missing in the screen folders. Now the program works on some screens but not the battle screens. The program will not play cards or retreat on its turn, how can I fix this?
> 
> You can't replace them all at once, you have to make sure to replace the original reference with a cropped image that is displaying the same UI element that the original reference image was displaying.
> 
> For example, if you wanted to update the image, you would have to run the bot in Conquest mode, wait until it reaches the Proving Grounds lobby screen, and then take the image that it captured from that view.`lbl-conquest-pg-1-preproc.png`
> 
> So while it is possible, I do think this would be a difficult task for someone who doesn't really understand the bot's operation. I have an idea on how I could build in a self-configuration tool so everyone can fix it on their own, but it will take me some time to put that together.

The program is now working, although in a way I don't understand. I will continue to replace the image in the next two days. Thank you for your answer.

**Comment by Kusaki-Y** [comment]
> > I replaced about half of the images but many of them are missing in the screen folders. Now the program works on some screens but not the battle screens. The program will not play cards or retreat on its turn, how can I fix this?
> 
> You can't replace them all at once, you have to make sure to replace the original reference with a cropped image that is displaying the same UI element that the original reference image was displaying.
> 
> For example, if you wanted to update the `lbl-conquest-pg-1-preproc.png` image, you would have to run the bot in Conquest mode, wait until it reaches the Proving Grounds lobby screen, and then take the image that it captured from that view.
> 
> So while it is possible, I do think this would be a difficult task for someone who doesn't really understand the bot's operation. I have an idea on how I could build in a self-configuration tool so everyone can fix it on their own, but it will take me some time to put that together.

I have made the Chinese stickers and the program can run normally, but how can I submit the file to you?

**Comment by Kusaki-Y** [comment]
> > I replaced about half of the images but many of them are missing in the screen folders. Now the program works on some screens but not the battle screens. The program will not play cards or retreat on its turn, how can I fix this?
> 
> You can't replace them all at once, you have to make sure to replace the original reference with a cropped image that is displaying the same UI element that the original reference image was displaying.
> 
> For example, if you wanted to update the `lbl-conquest-pg-1-preproc.png` image, you would have to run the bot in Conquest mode, wait until it reaches the Proving Grounds lobby screen, and then take the image that it captured from that view.
> 
> So while it is possible, I do think this would be a difficult task for someone who doesn't really understand the bot's operation. I have an idea on how I could build in a self-configuration tool so everyone can fix it on their own, but it will take me some time to put that together.

https://github.com/Kusaki-Y/booster-bot/tree/main/src/BoosterBot/Reference

**Comment by holletian** [comment]
> > https://github.com/Kusaki-Y/booster-bot/tree/main/src/BoosterBot/Reference
> 
> 令人印象深刻！对于遇到问题的其他 CN 玩家，请尝试下载此处链接的图像并将其放在程序的`Reference`目录中，看看它是否能恢复功能。看起来游戏的语言也应该设置为中文而不是英语

It's running normally. Thanks.

**Comment by Kusaki-Y** [comment]
> > https://github.com/Kusaki-Y/booster-bot/tree/main/src/BoosterBot/Reference
> 
> Impressive! For any other CN players having issues, try downloading the images linked here and placing them in the program's `Reference` directory to see if it restores functionality. Looks like the game's language should also be set to Chinese instead of English

In fact, there are problems with several images. I am not sure if I have replaced the two files btn-conquest-continue-preproc.png and btn-conquest-concede-preproc.png correctly. Please explain how these two files appear in the game.

**Comment by little-fort** [comment]
btn-conquest-continue-preproc.png is no longer used—that post-match screen was removed in a recent patch. btn-conquest-concede-preproc.png is for the 'Concede' button that is shown in-between Conquest rounds:

![image](https://github.com/user-attachments/assets/56cb98e0-67b9-4e3d-947f-bf45c6a2ad43)

**Comment by Kusaki-Y** [comment]
> btn-conquest-continue-preproc.png is no longer used—that post-match screen was removed in a recent patch. btn-conquest-concede-preproc.png is for the 'Concede' button that is shown in-between Conquest rounds:
> 
> ![image](https://private-user-images.githubusercontent.com/39720285/389173109-56cb98e0-67b9-4e3d-947f-bf45c6a2ad43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNDM2NzIsIm5iZiI6MTczMjM0MzM3MiwicGF0aCI6Ii8zOTcyMDI4NS8zODkxNzMxMDktNTZjYjk4ZTAtNjdiOS00ZTNkLTk0N2YtYmY0NWM2YTJhZDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDA2MjkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxYWI2Y2U3ZGRmMDA1YjE5Nzk4MWFlNWUxNzg2Zjk5YjkzMDhlYjVlZTFkYzdlMDczY2RkZjRkODg4ZDQyMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IbfXPcO2smlg6hnRy9-nDhysxMwq8Q9HA3dRQ_xvJj0)

little-fort, I have an idea. Can you add a Chinese reference folder to the program and choose Chinese or English to select different reference folders before running? Is it feasible?

**Comment by Kusaki-Y** [comment]
> > btn-conquest-continue-preproc.png is no longer used—that post-match screen was removed in a recent patch. btn-conquest-concede-preproc.png is for the 'Concede' button that is shown in-between Conquest rounds:
> > ![image](https://private-user-images.githubusercontent.com/39720285/389173109-56cb98e0-67b9-4e3d-947f-bf45c6a2ad43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNDM2NzIsIm5iZiI6MTczMjM0MzM3MiwicGF0aCI6Ii8zOTcyMDI4NS8zODkxNzMxMDktNTZjYjk4ZTAtNjdiOS00ZTNkLTk0N2YtYmY0NWM2YTJhZDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDA2MjkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxYWI2Y2U3ZGRmMDA1YjE5Nzk4MWFlNWUxNzg2Zjk5YjkzMDhlYjVlZTFkYzdlMDczY2RkZjRkODg4ZDQyMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IbfXPcO2smlg6hnRy9-nDhysxMwq8Q9HA3dRQ_xvJj0)
> 
> little-fort, I have an idea. Can you add a Chinese reference folder to the program and choose Chinese or English to select different reference folders before running? Is it feasible?

And, boss, thank you for your answers all the time.hhh

**Comment by little-fort** [comment]
> little-fort, I have an idea. Can you add a Chinese reference folder to the program and choose Chinese or English to select different reference folders before running? Is it feasible?

Yes, that is my plan and part of what I'm currently working on 🙂

I have already finished work on a new repair function so that anyone will be able to easily fix the reference images on their own system in case another update breaks the references again.  I am also adding a permanent configuration file to the app folder so that users can modify settings that will be remembered between runs rather than relying on command line arguments only. 

One of the settings I am adding is for alternate languages... I'm relying on Google Translate so I know it won't be perfect, but I hope it will make using the bot (and the game) a little easier for all of you

![image](https://github.com/user-attachments/assets/265c33a7-6d6e-42b3-9cd9-a6a433ae1826)

**Comment by little-fort** [comment]
Hello all, I have published a new release: https://github.com/little-fort/booster-bot/releases/tag/v1.6.0

This update contains my first attempt at localizing the program's text for Chinese users—you will be prompted to configure language selections on the first program start. The translations were made using Google Translate so I'm sure there will be many inaccuracies, but I will be happy to add any suggested improvements that can make the text easier to understand.

I have also bundled the images from @Kusaki-Y in this release for those who have the game set to Chinese text. For anyone else (or if you are encountering issues), this release also contains a new "Repair Mode" that can be activated by starting the program with the `--repair` parameter. This will walk you through the steps needed to manually capture the relevant components of the game interface as they appear on your specific system.

Please try the latest version and let me know if you encounter further issues. These are substantial changes to the codebase, so I expect there will be issues as more people use it, but I hope you are able to find the core functionality restored with this update

**Comment by Kusaki-Y** [comment]
> Hello all, I have published a new release: https://github.com/little-fort/booster-bot/releases/tag/v1.6.0
> 
> This update contains my first attempt at localizing the program's text for Chinese users—you will be prompted to configure language selections on the first program start. The translations were made using Google Translate so I'm sure there will be many inaccuracies, but I will be happy to add any suggested improvements that can make the text easier to understand.
> 
> I have also bundled the images from @Kusaki-Y in this release for those who have the game set to Chinese text. For anyone else (or if you are encountering issues), this release also contains a new "Repair Mode" that can be activated by starting the program with the `--repair` parameter. This will walk you through the steps needed to manually capture the relevant components of the game interface as they appear on your specific system.
> 
> Please try the latest version and let me know if you encounter further issues. These are substantial changes to the codebase, so I expect there will be issues as more people use it, but I hope you are able to find the core functionality restored with this update

I updated the Chinese pictures a few days ago, but forgot to put them into GitHub. It happened that I was on a business trip these two days and couldn’t upload them. I will test the program later and contact you in time if there are any problems. Thank you for your help!

**Comment by Kusaki-Y** [comment]
> Hello all, I have published a new release: https://github.com/little-fort/booster-bot/releases/tag/v1.6.0
> 
> This update contains my first attempt at localizing the program's text for Chinese users—you will be prompted to configure language selections on the first program start. The translations were made using Google Translate so I'm sure there will be many inaccuracies, but I will be happy to add any suggested improvements that can make the text easier to understand.
> 
> I have also bundled the images from @Kusaki-Y in this release for those who have the game set to Chinese text. For anyone else (or if you are encountering issues), this release also contains a new "Repair Mode" that can be activated by starting the program with the `--repair` parameter. This will walk you through the steps needed to manually capture the relevant components of the game interface as they appear on your specific system.
> 
> Please try the latest version and let me know if you encounter further issues. These are substantial changes to the codebase, so I expect there will be issues as more people use it, but I hope you are able to find the core functionality restored with this update

I’m looking forward to using this new feature, it looks like it will be really useful!As for the Chinese translation, I think there is no problem. Thank you for your effort to check the Chinese. Chinese should be quite difficult for non-native speakers.

**Comment by Kusaki-Y** [comment]
> Hello all, I have published a new release: https://github.com/little-fort/booster-bot/releases/tag/v1.6.0
> 
> This update contains my first attempt at localizing the program's text for Chinese users—you will be prompted to configure language selections on the first program start. The translations were made using Google Translate so I'm sure there will be many inaccuracies, but I will be happy to add any suggested improvements that can make the text easier to understand.
> 
> I have also bundled the images from @Kusaki-Y in this release for those who have the game set to Chinese text. For anyone else (or if you are encountering issues), this release also contains a new "Repair Mode" that can be activated by starting the program with the `--repair` parameter. This will walk you through the steps needed to manually capture the relevant components of the game interface as they appear on your specific system.
> 
> Please try the latest version and let me know if you encounter further issues. These are substantial changes to the codebase, so I expect there will be issues as more people use it, but I hope you are able to find the core functionality restored with this update

![mmexport1732720949761](https://github.com/user-attachments/assets/026ac309-3bb3-49d7-a987-f9388e83ea85)
Fixed the problem that the function recognition position is different from the position recognized when the program is run independently

**Comment by Kusaki-Y** [comment]
> Hello all, I have published a new release: https://github.com/little-fort/booster-bot/releases/tag/v1.6.0
> 
> This update contains my first attempt at localizing the program's text for Chinese users—you will be prompted to configure language selections on the first program start. The translations were made using Google Translate so I'm sure there will be many inaccuracies, but I will be happy to add any suggested improvements that can make the text easier to understand.
> 
> I have also bundled the images from @Kusaki-Y in this release for those who have the game set to Chinese text. For anyone else (or if you are encountering issues), this release also contains a new "Repair Mode" that can be activated by starting the program with the `--repair` parameter. This will walk you through the steps needed to manually capture the relevant components of the game interface as they appear on your specific system.
> 
> Please try the latest version and let me know if you encounter further issues. These are substantial changes to the codebase, so I expect there will be issues as more people use it, but I hope you are able to find the core functionality restored with this update

Another issue is that the second battle of the silver game in conquest mode is often not recognized. This may be a problem with silver-3.png.

**Comment by Kusaki-Y** [comment]
> Hello all, I have published a new release: https://github.com/little-fort/booster-bot/releases/tag/v1.6.0
> 
> This update contains my first attempt at localizing the program's text for Chinese users—you will be prompted to configure language selections on the first program start. The translations were made using Google Translate so I'm sure there will be many inaccuracies, but I will be happy to add any suggested improvements that can make the text easier to understand.
> 
> I have also bundled the images from @Kusaki-Y in this release for those who have the game set to Chinese text. For anyone else (or if you are encountering issues), this release also contains a new "Repair Mode" that can be activated by starting the program with the `--repair` parameter. This will walk you through the steps needed to manually capture the relevant components of the game interface as they appear on your specific system.
> 
> Please try the latest version and let me know if you encounter further issues. These are substantial changes to the codebase, so I expect there will be issues as more people use it, but I hope you are able to find the core functionality restored with this update

Perhaps the range of lbl-conquest-xxxx-3-preproc.png for the Chinese version needs to be reduced a bit, because there are dynamic special effects around the text, which causes the black pixels in the background of the screens image to keep changing and is different from the images in the reference folder.

**Comment by Kusaki-Y** [comment]
> Hello all, I have published a new release: https://github.com/little-fort/booster-bot/releases/tag/v1.6.0
> 
> This update contains my first attempt at localizing the program's text for Chinese users—you will be prompted to configure language selections on the first program start. The translations were made using Google Translate so I'm sure there will be many inaccuracies, but I will be happy to add any suggested improvements that can make the text easier to understand.
> 
> I have also bundled the images from @Kusaki-Y in this release for those who have the game set to Chinese text. For anyone else (or if you are encountering issues), this release also contains a new "Repair Mode" that can be activated by starting the program with the `--repair` parameter. This will walk you through the steps needed to manually capture the relevant components of the game interface as they appear on your specific system.
> 
> Please try the latest version and let me know if you encounter further issues. These are substantial changes to the codebase, so I expect there will be issues as more people use it, but I hope you are able to find the core functionality restored with this update

Maybe we can design a function that allows players to choose the image size themselves。Or set a function that can adjust the accuracy of program recognition.

**Comment by Kusaki-Y** [comment]
![Image_57140377175493](https://github.com/user-attachments/assets/e701b885-faf1-4220-95d2-49f69c8d01fb)
The pictures in the reference have been updated.

**Comment by little-fort** [comment]
> Fixed the problem that the function recognition position is different from the position recognized when the program is run independently

It's actually okay if the text is not exactly centered in the cropped image. As long as the overall result is uniquely identifiable, we will still get the desired result

> Another issue is that the second battle of the silver game in conquest mode is often not recognized. This may be a problem with silver-3.png.

Yes, the silver-3/gold-3/infinite-3 images are generally used to identify the lobby during an active run. I wasn't sure about adding a step to fix that in the repair mode function because it would require the user to enter into a lobby even if they don't intend to play it out, and I was hesitant to prompt players to waste a ticket like that.

> Perhaps the range of lbl-conquest-xxxx-3-preproc.png for the Chinese version needs to be reduced a bit, because there are dynamic special effects around the text, which causes the black pixels in the background of the screens image to keep changing and is different from the images in the reference folder.

This is a very interesting observation... If there are a lot of text effects, that will definitely interfere with detection. I would suggest trying with the "downscaled" option enabled, as it will reduce the thresholds necessary to match UI components, and may help text get recognized even if the effects create variance

**Comment by Kusaki-Y** [comment]
> > Fixed the problem that the function recognition position is different from the position recognized when the program is run independently
> 
> It's actually okay if the text is not exactly centered in the cropped image. As long as the overall result is uniquely identifiable, we will still get the desired result
> 
> > Another issue is that the second battle of the silver game in conquest mode is often not recognized. This may be a problem with silver-3.png.
> 
> Yes, the silver-3/gold-3/infinite-3 images are generally used to identify the lobby during an active run. I wasn't sure about adding a step to fix that in the repair mode function because it would require the user to enter into a lobby even if they don't intend to play it out, and I was hesitant to prompt players to waste a ticket like that.
> 
> > Perhaps the range of lbl-conquest-xxxx-3-preproc.png for the Chinese version needs to be reduced a bit, because there are dynamic special effects around the text, which causes the black pixels in the background of the screens image to keep changing and is different from the images in the reference folder.
> 
> This is a very interesting observation... If there are a lot of text effects, that will definitely interfere with detection. I would suggest trying with the "downscaled" option enabled, as it will reduce the thresholds necessary to match UI components, and may help text get recognized even if the effects create variance

Boss, Maybe you can't imagine how enthusiastic Chinese players are about using your program. In 1-3 nights, the number of silver and gold tickets can reach 99.Many people are also discussing how to solve some problems encountered during use.So everyone is waiting for your update.hhh

**Comment by Kusaki-Y** [comment]
So, can you help us adjust the size of the 3rd reference image in Conquest? Or maybe tell me how to adjust the code to customize the reference image size.We will be grateful.

**Comment by little-fort** [comment]
> So, can you help us adjust the size of the 3rd reference image in Conquest? Or maybe tell me how to adjust the code to customize the reference image size.We will be grateful.

I am finalizing a new release now, I'd like to test this new release first and then if the 3rd reference image is still an issue. I have adjusted the logic slightly so that it will default to continuing an active run that is detected rather than trying to identify the lobby again

I have also added a separate reference point for the lobby entry that should hopefully be more reliable

**Comment by Kusaki-Y** [comment]
I am revising the Chinese translation and will upload it to the warehouse today.
![Uploading Image_11841995044909.png…]()

**Comment by Kusaki-Y** [comment]
![Uploading Image_11841995044909.png…]()

**Comment by Kusaki-Y** [comment]
The Chinese translation of Strings.zh-CN.resx has been revised and is ready to be uploaded to the repository

**Comment by Kusaki-Y** [comment]
The upload has been completed 
![Uploading QQ截图20241130163712.png…]()
https://github.com/Kusaki-Y/booster-bot/blob/main/src/BoosterBot/Resources/Strings.zh-CN.resx

**Comment by Kusaki-Y** [comment]
> > So, can you help us adjust the size of the 3rd reference image in Conquest? Or maybe tell me how to adjust the code to customize the reference image size.We will be grateful.
> 
> I am finalizing a new release now, I'd like to test this new release first to see if the 3rd reference image is still an issue. I have adjusted the logic slightly so that it will default to continuing an active run that is detected rather than trying to identify the lobby type again
> 
> I have also added a separate reference point for the lobby entry that should hopefully be more reliable

I'm not sure if it's a code error or an image error. When the lbl-conquest-XXXX-3-preproc.png in the reference folder is the wrong image, the program can continue to run and continue the battle.

**Comment by little-fort** [comment]
> I'm not sure if it's a code error or an image error. When the lbl-conquest-XXXX-3-preproc.png in the reference folder is the wrong image, the program can continue to run and continue the battle.

Yes that is fine. The only time that image is used is when a Conquest session is already in progress. It is used to verify the session level before proceeding. But that is only used as a safeguard and is not necessary for the program to function

**Comment by little-fort** [comment]
I have published a new release with various fixes and adjustments, please try using it and let me know if you find more issues:

https://github.com/little-fort/booster-bot/releases/tag/v1.6.1

Thank you for your contributions @Kusaki-Y! I have included them in the build, but I would expect most users may still have to use repair mode to correct differences on their personal machine

**Comment by Kusaki-Y** [comment]
> I have published a new release with various fixes and adjustments, please try using it and let me know if you find more issues:
> 
> https://github.com/little-fort/booster-bot/releases/tag/v1.6.1
> 
> Thank you for your contributions @Kusaki-Y! I have included them in the build, but I would expect most users may still have to use repair mode to correct differences on their personal machine

My friend, maybe you can use Alipay to get donations, because Chinese players may not have bank cards from other countries, hahaha. The latest program runs very smoothly, here I would like to express my gratitude to you on behalf of me and my friends. I found that the new program will reconfirm the current mode after finishing a game of conquest mode, slide the window and then re-play the game. I feel that this will make the efficiency lower. Perhaps the number of sliding windows can be reduced to improve efficiency. I have uploaded the latest Chinese reference file, please check it.

**Comment by rxyhgmgly123** [comment]
I am a subtitle editor for the Chinese version of a software, and I have noticed that compared to Chinese, English subtitles are recognized more quickly and accurately. I would like to ask how to create language folders for other options so that I can select between Chinese, English, and other options such as Chinese with English language settings.
 
Please excuse any awkward sentences as this was translated using software.
