### ISSUE TITLE
How can I modify the settings to allow the program to run for a longer duration

### ISSUE THREAD

**Issue by jxkanggit** [little-fort/booster-bot#80]
I noticed that the program terminates due to the condition “Hard limit of 1000 boosters per day still applies.” How can I modify the settings to allow the program to run for a longer duration? I need to go to school, so I can only operate my computer every two to three days, and I have a strong need for the program to run for extended periods.

**Comment by little-fort** [comment]
Hi, that condition only affects in-game rewards—it doesn't have any impact on the execution of the program. If the program is being terminated unexpectedly, there would have to be another cause. Can you provide a log file from a run where it terminated too quickly?

**Comment by jxkanggit** [comment]
Thank you for your reply. I think my problem may be caused by my use of a virtual machine. My virtual machine may not be very stable.
