### ISSUE TITLE
My script could not detect the main menu

### ISSUE THREAD

**Issue by wusihua1** [little-fort/booster-bot#81]
I am a player from zh,I correctly used a resolution of 1920 x 1080 and tried various instructions to start the script, but it still couldn't run correctly,I have reviewed the issue of the same problem, but it still cannot be resolved, so I have uploaded  screens and log files. Could you please take a look at what the problem is?thanks
![image](https://github.com/user-attachments/assets/e521e31f-c5d2-4962-84fc-8f2b47f56ab1)
[screens.zip](https://github.com/user-attachments/files/17873840/screens.zip)
[logs.zip](https://github.com/user-attachments/files/17873855/logs.zip)

**Comment by wusihua1** [comment]
I also want to ask, is there a problem with writing the cmd command like this，\BoosterBot.exe -m c -ct s -t 6

**Comment by Kusaki-Y** [comment]
> I also want to ask, is there a problem with writing the cmd command like this，\BoosterBot.exe -m c -ct s -t 6

国服中文版已更新，位置百度贴吧

**Comment by little-fort** [comment]
> I also want to ask, is there a problem with writing the cmd command like this，\BoosterBot.exe -m c -ct s -t 6

There is no problem with this command, I just tested it myself and it works fine

As for your initial issue with menu detection, this is happening for the reason that @Kusaki-Y mentioned. There was an update this week for ZH players that broke the program functions. I am currently working on fixes that should be ready for release in the next couple days

**Comment by little-fort** [comment]
Hi @wusihua1, please try the latest version with the game set to Chinese text: https://github.com/little-fort/booster-bot/releases/tag/v1.6.0

If you still encounter issues, start the program with the new repair command like so: `BoosterBot.exe --repair`

This will walk you through the steps needed to let the program configure itself and correct the interface detection

**Comment by wusihua1** [comment]
> Hi @wusihua1, please try the latest version with the game set to Chinese text: https://github.com/little-fort/booster-bot/releases/tag/v1.6.0
> 
> If you still encounter issues, start the program with the new repair command like so: `BoosterBot.exe --repair`
> 
> This will walk you through the steps needed to let the program configure itself and correct the interface detection

thanks, I'll give it a try

**Comment by gyh922** [comment]
Hi Sir, first of all thank you for all the things you are doing, we sincerely appreciate it!

I'm also from the ZH community so obviously the bot is not working, i downloaded ver 1.6.0 and tried the repair mode you mentioned to other user, unfortunately it keeps flashes Error messages.

I heard from some users that this might have something to do with the latest ZH PC client changed some fonts, dont know if you already aware of it or not, hopefully it can help.

THANK YOU for your effort and look forward to updates.

![111](https://github.com/user-attachments/assets/c10b04fd-023e-49de-a0df-ed52cd47e10d)

**Comment by Kusaki-Y** [comment]
> Hi Sir, first of all thank you for all the things you are doing, we sincerely appreciate it!
> 
> I'm also from the ZH community so obviously the bot is not working, i downloaded ver 1.6.0 and tried the repair mode you mentioned to other user, unfortunately it keeps flashes Error messages.
> 
> I heard from some users that this might have something to do with the latest ZH PC client changed some fonts, dont know if you already aware of it or not, hopefully it can help.
> 
> THANK YOU for your effort and look forward to updates.
> 
> ![111](https://private-user-images.githubusercontent.com/43773198/390647080-c10b04fd-023e-49de-a0df-ed52cd47e10d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3OTYyOTIsIm5iZiI6MTczMjc5NTk5MiwicGF0aCI6Ii80Mzc3MzE5OC8zOTA2NDcwODAtYzEwYjA0ZmQtMDIzZS00OWRlLWEwZGYtZWQ1MmNkNDdlMTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDEyMTMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YjAyYTg4NDExYzkxNDEzMDg1NWIwZmFhZmJhYzIwMzNkYTNmMWQ0NGZhMTQwNTQ1OTM3ZDZlZjYyZmYzYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.G7gnsGzDrPtEaiZNXxIhPM7_GhsahM7RjHFs77acXuA)

我尝试了1.6.0的修复功能，修复时剪切出来的图片和脚本自己运行剪切的位置有差异，和游戏无关。至于脚本有时无法识别，可能跟动态的特效有关。

**Comment by gyh922** [comment]
> > Hi Sir, first of all thank you for all the things you are doing, we sincerely appreciate it!
> > I'm also from the ZH community so obviously the bot is not working, i downloaded ver 1.6.0 and tried the repair mode you mentioned to other user, unfortunately it keeps flashes Error messages.
> > I heard from some users that this might have something to do with the latest ZH PC client changed some fonts, dont know if you already aware of it or not, hopefully it can help.
> > THANK YOU for your effort and look forward to updates.
> > ![111](https://private-user-images.githubusercontent.com/43773198/390647080-c10b04fd-023e-49de-a0df-ed52cd47e10d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3OTYyOTIsIm5iZiI6MTczMjc5NTk5MiwicGF0aCI6Ii80Mzc3MzE5OC8zOTA2NDcwODAtYzEwYjA0ZmQtMDIzZS00OWRlLWEwZGYtZWQ1MmNkNDdlMTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDEyMTMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YjAyYTg4NDExYzkxNDEzMDg1NWIwZmFhZmJhYzIwMzNkYTNmMWQ0NGZhMTQwNTQ1OTM3ZDZlZjYyZmYzYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.G7gnsGzDrPtEaiZNXxIhPM7_GhsahM7RjHFs77acXuA)
> 
> 我尝试了1.6.0的修复功能，修复时剪切出来的图片和脚本自己运行剪切的位置有差异，和游戏无关。至于脚本有时无法识别，可能跟动态的特效有关。

很不幸我连修复功能都使用不了，看起来只能等开发者的更新了...

**Comment by little-fort** [comment]
Hi, I have published a new release with various fixes and adjustments, please try using it and let me know if you find more issues:

https://github.com/little-fort/booster-bot/releases/tag/v1.6.1

**Comment by gyh922** [comment]
> Hi, I have published a new release with various fixes and adjustments, please try using it and let me know if you find more issues:
> 
> https://github.com/little-fort/booster-bot/releases/tag/v1.6.1

Much Appreciated!

Just tried v1.6.1, it didn't work at first, I used repair mode and went through the end, it's working now!

**Comment by little-fort** [comment]
> Just tried v1.6.1, it didn't work at first, I used repair mode and went through the end, it's working now!

Great! I'm glad to hear that
