### ISSUE TITLE
Visual Studio 2022 builds the console program

### ISSUE THREAD

**Issue by Kusaki-Y** [little-fort/booster-bot#93]
When I use Visual Studio 2022 to build the console program, others can't use it, what are the missing steps?
![Image_41822063865972](https://github.com/user-attachments/assets/ef774a4a-f89b-4a8f-acd0-b43fefea81be)
![Image_41817038924984](https://github.com/user-attachments/assets/62b5e749-e6f7-4579-8b62-6d959ed133a4)

**Comment by little-fort** [comment]
I'm guessing this is because they do not have the .NET 8 SDK installed on their machine. If you want to create your own build to distribute, make sure to use the Publish option and then configure the publish profile to produce a self-contained build like so:

![image](https://github.com/user-attachments/assets/f2ad47e8-f844-4785-86f5-72a4f3121863)

**Comment by Kusaki-Y** [comment]
![Image_8109303921696](https://github.com/user-attachments/assets/1a8d6e8d-0be0-4a8f-bef4-f246498e401e)


> I'm guessing this is because they do not have the .NET 8 SDK installed on their machine. If you want to create your own build to distribute, make sure to use the Publish option and then configure the publish profile to produce a self-contained build like so:
> 
> ![image](https://private-user-images.githubusercontent.com/39720285/392152625-f2ad47e8-f844-4785-86f5-72a4f3121863.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNzc4MzEsIm5iZiI6MTczMzI3NzUzMSwicGF0aCI6Ii8zOTcyMDI4NS8zOTIxNTI2MjUtZjJhZDQ3ZTgtZjg0NC00Nzg1LTg2ZjUtNzJhNGYzMTIxODYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDAxNTg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyOGNjYTcyNTYwNzBkN2M2YWVkYjg4ZmUxMzk4Njg0YzM1ZGE4OTI2ZTYxZWY3ZGQ3NDgzZWIxNmMyZWQ4NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8T0e7wrrfoxhIhahc62oGsW20R8bmlMPa0QwRJ-U9s8)


Brother, how to solve this problem?
![Image_8109303921696](https://github.com/user-attachments/assets/fa2e480e-2354-4a16-9609-ede017d9d5c5)

**Comment by Kusaki-Y** [comment]
> ![Image_8109303921696](https://private-user-images.githubusercontent.com/187355382/392197416-1a8d6e8d-0be0-4a8f-bef4-f246498e401e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyOTAyNjIsIm5iZiI6MTczMzI4OTk2MiwicGF0aCI6Ii8xODczNTUzODIvMzkyMTk3NDE2LTFhOGQ2ZThkLTBiZTAtNGE4Zi1iZWY0LWYyNDY0OThlNDAxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQwNTI2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGI5YmU4MjQxNzQxZGY4YjVlMDE4NWE5NGFkMTExOWE2MGE4Yzk0OGEwMTc3NjQxZThiNWQ2YmZjYWY4NDY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-_0ejEMEjC-0OyZjYma5wwH62o9EV96fI-PlBXUIso8)
> 
> > I'm guessing this is because they do not have the .NET 8 SDK installed on their machine. If you want to create your own build to distribute, make sure to use the Publish option and then configure the publish profile to produce a self-contained build like so:
> > ![image](https://private-user-images.githubusercontent.com/39720285/392152625-f2ad47e8-f844-4785-86f5-72a4f3121863.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNzc4MzEsIm5iZiI6MTczMzI3NzUzMSwicGF0aCI6Ii8zOTcyMDI4NS8zOTIxNTI2MjUtZjJhZDQ3ZTgtZjg0NC00Nzg1LTg2ZjUtNzJhNGYzMTIxODYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDAxNTg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyOGNjYTcyNTYwNzBkN2M2YWVkYjg4ZmUxMzk4Njg0YzM1ZGE4OTI2ZTYxZWY3ZGQ3NDgzZWIxNmMyZWQ4NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8T0e7wrrfoxhIhahc62oGsW20R8bmlMPa0QwRJ-U9s8)
> 
> Brother, how to solve this problem? ![Image_8109303921696](https://private-user-images.githubusercontent.com/187355382/392197837-fa2e480e-2354-4a16-9609-ede017d9d5c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyOTAyNjIsIm5iZiI6MTczMzI4OTk2MiwicGF0aCI6Ii8xODczNTUzODIvMzkyMTk3ODM3LWZhMmU0ODBlLTIzNTQtNGExNi05NjA5LWVkZTAxN2Q5ZDVjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQwNTI2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTZkNjAwZmJlYTFlZGYzZDVhOTRlN2FiNGM5MTE1NDUyZGMzY2VmYzZiYmJhNjA5NDgxNmFiMDY2NmVhYWI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QVpmXBuPC4OEbRU-OEniLKoC9DY4jGxuGvFxO92anDo)

It's been solved, I've shortened the settlement time, and I feel that the operation efficiency has improved a lot.

**Comment by Kusaki-Y** [comment]
> I'm guessing this is because they do not have the .NET 8 SDK installed on their machine. If you want to create your own build to distribute, make sure to use the Publish option and then configure the publish profile to produce a self-contained build like so:
> 
> ![image](https://private-user-images.githubusercontent.com/39720285/392152625-f2ad47e8-f844-4785-86f5-72a4f3121863.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjAxODgsIm5iZiI6MTczMzMxOTg4OCwicGF0aCI6Ii8zOTcyMDI4NS8zOTIxNTI2MjUtZjJhZDQ3ZTgtZjg0NC00Nzg1LTg2ZjUtNzJhNGYzMTIxODYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDEzNDQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYzdkYzVlNTEwMTE4ODQ4NTMyOGM5YTQzYzdlZGQzNjQyNDE2YTY1ODVlZDY3MmZmNDc2MDk5ZWIxMDg5MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rYd3mqScTDwBqB2wZp2bO8-G3-9wb4NakaC71kRdNag)
Hello, in the conquestbot.cs file, I've added Chinese comments specifically for Chinese players and reduced the Thread.sleep time in multiple places to decrease the number of slides in the conquest lobby. Currently, running on snapcn.exe is very smooth, with each conquest mode game lasting about three minutes. I've also adjusted the time limit for game sessions, allowing more people to use the 3-4 round retreat function and earn rewards and experience faster. The downside is that the no-retreat function is now limited by time, but overall, the benefits outweigh the drawbacks.
![Screenshot_20241204_213125](https://github.com/user-attachments/assets/a6399aa0-6474-48e5-bab4-89fabd6e5651)

**Comment by Kusaki-Y** [comment]
> I'm guessing this is because they do not have the .NET 8 SDK installed on their machine. If you want to create your own build to distribute, make sure to use the Publish option and then configure the publish profile to produce a self-contained build like so:
> 
> ![image](https://private-user-images.githubusercontent.com/39720285/392152625-f2ad47e8-f844-4785-86f5-72a4f3121863.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjAxODgsIm5iZiI6MTczMzMxOTg4OCwicGF0aCI6Ii8zOTcyMDI4NS8zOTIxNTI2MjUtZjJhZDQ3ZTgtZjg0NC00Nzg1LTg2ZjUtNzJhNGYzMTIxODYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDEzNDQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYzdkYzVlNTEwMTE4ODQ4NTMyOGM5YTQzYzdlZGQzNjQyNDE2YTY1ODVlZDY3MmZmNDc2MDk5ZWIxMDg5MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rYd3mqScTDwBqB2wZp2bO8-G3-9wb4NakaC71kRdNag)

Hello, I added Chinese comments for Chinese players in the conquestbot.cs file and reduced the Thread.sleep time at multiple points. I also decreased the number of sliding actions in the Conquest Hall. Currently, the game runs very smoothly on snapcn.exe, with each Conquest mode game being controlled within three minutes. At the same time, I adjusted the time limit for Conquest mode games, allowing more people to use the 3-4 round retreat function and obtain rewards and experience faster. The downside is that the non-retreat option is now time-limited, but overall, the benefits outweigh the drawbacks.
![Screenshot_20241204_213125](https://github.com/user-attachments/assets/531f4441-41b2-4245-b050-70d9b92ffa7d)
